export const USER_INFO = 'USER_INFO'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_SEND_VERIFY = 'USER_SEND_VERIFY'
export const USER_REGISTE = 'USER_REGISTE'
export const USER_RESET_PASS = 'USER_RESET_PASS'
export const USER_LOGOUT = 'USER_LOGOUT'
